resources:
  - namespace.yaml
  - deployment-kernel.yaml
  - service-kernel.yaml
  - ingress.yaml
  - pvc-provisioning.yaml
  - job-download.yaml
  - job-stage-rhel-iso.yaml
  - job-extract-rhel-repo.yaml
  - ../../../configs/provisioning


