apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-proxy-config
  namespace: dnsmasq
data:
  dnsmasq.conf: |
    port=0
    log-dhcp
    log-facility=-

    dhcp-range=192.168.1.0,proxy

    dhcp-match=set:efi-x86_64,option:client-arch,7
    dhcp-match=set:bios,option:client-arch,0

    pxe-service=x86PC,"Boot BIOS",undionly.kpxe,192.168.1.70
    pxe-service=X86-64_EFI,"Boot UEFI",ipxe.efi,192.168.1.70

    interface=enp2s0
    bind-interfaces
