apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-proxy-config
  namespace: dnsmasq
data:
  dnsmasq.conf: |
    port=0
    log-dhcp
    log-facility=-

    dhcp-range=192.168.1.0,proxy

    # Detectar arquitectura
    dhcp-match=set:efi-x86_64,option:client-arch,7
    dhcp-match=set:bios,option:client-arch,0

    # Detectar iPXE ya corriendo
    dhcp-userclass=set:ipxe,iPXE

    # iPXE corriendo: forzar el script HTTP via option 67
    dhcp-option=tag:ipxe,option:bootfile-name,http://boot.local/ipxe/menu.ipxe

    # Primera pasada UEFI (sin iPXE)
    dhcp-boot=tag:efi-x86_64,tag:!ipxe,ipxe.efi,,192.168.1.70

    # Primera pasada BIOS (sin iPXE)
    dhcp-boot=tag:bios,tag:!ipxe,undionly.kpxe,,192.168.1.70

    interface=enp2s0
    bind-interfaces
