apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tang
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SirXavor/InfraServer.git
    targetRevision: main
    path: manifests/infraserver/tang
  destination:
    server: https://kubernetes.default.svc
    namespace: tang
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
