apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: dns
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.71
  externalTrafficPolicy: Local
  selector:
    app: coredns
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
