apiVersion: v1
kind: Service
metadata:
  name: infrawriter-api
  namespace: infrawriter
spec:
  selector:
    app: infrawriter-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP