autoinstall:
  version: 1

  storage:
    config:
      - id: disk-sda
        type: disk
        path: /dev/sda
        ptable: gpt
        wipe: superblock-recursive
        grub_device: true

      - id: part-efi
        type: partition
        device: disk-sda
        size: 512M
        flag: esp
        grub_device: true

      - id: part-boot
        type: partition
        device: disk-sda
        size: 2G

      - id: part-root-crypt
        type: partition
        device: disk-sda
        size: -1

      - id: fs-efi
        type: format
        volume: part-efi
        fstype: fat32

      - id: fs-boot
        type: format
        volume: part-boot
        fstype: ext4

      - id: luks-root
        type: dm_crypt
        volume: part-root-crypt
        key: "InfraK3s-2026!"
        cipher: aes-xts-plain64
        keysize: 512

      - id: vg-system
        type: lvm_volgroup
        name: vg_system
        devices:
          - luks-root

      - id: lv-root
        type: lvm_partition
        name: lv_root
        volgroup: vg-system
        size: 30G

      - id: lv-varlog
        type: lvm_partition
        name: lv_varlog
        volgroup: vg-system
        size: 10G

      - id: lv-tmp
        type: lvm_partition
        name: lv_tmp
        volgroup: vg-system
        size: 8G

      - id: lv-vartmp
        type: lvm_partition
        name: lv_vartmp
        volgroup: vg-system
        size: 8G

      - id: lv-home
        type: lvm_partition
        name: lv_home
        volgroup: vg-system
        size: 10G

      - id: lv-swap
        type: lvm_partition
        name: lv_swap
        volgroup: vg-system
        size: 8G

      - id: lv-var
        type: lvm_partition
        name: lv_var
        volgroup: vg-system
        size: -1

      - id: fs-root
        type: format
        volume: lv-root
        fstype: ext4

      - id: fs-varlog
        type: format
        volume: lv-varlog
        fstype: ext4

      - id: fs-tmp
        type: format
        volume: lv-tmp
        fstype: ext4

      - id: fs-vartmp
        type: format
        volume: lv-vartmp
        fstype: ext4

      - id: fs-home
        type: format
        volume: lv-home
        fstype: ext4

      - id: fs-swap
        type: format
        volume: lv-swap
        fstype: swap

      - id: fs-var
        type: format
        volume: lv-var
        fstype: ext4

      - id: mnt-efi
        type: mount
        device: fs-efi
        path: /boot/efi

      - id: mnt-boot
        type: mount
        device: fs-boot
        path: /boot

      - id: mnt-root
        type: mount
        device: fs-root
        path: /

      - id: mnt-varlog
        type: mount
        device: fs-varlog
        path: /var/log

      - id: mnt-tmp
        type: mount
        device: fs-tmp
        path: /tmp

      - id: mnt-vartmp
        type: mount
        device: fs-vartmp
        path: /var/tmp

      - id: mnt-home
        type: mount
        device: fs-home
        path: /home

      - id: mnt-var
        type: mount
        device: fs-var
        path: /var

  late-commands:

    - |
      curtin in-target --target=/target -- bash -c '
        set -e

        echo "[INFO] Instalando clevis + TPM..."
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y clevis clevis-initramfs clevis-luks clevis-tpm2 tpm2-tools cryptsetup-initramfs

        echo "[INFO] Limpiando posible lockout TPM..."
        tpm2_dictionarylockout --clear-lockout || true

        echo "[INFO] Haciendo bind LUKS -> TPM..."

        TMPKEY=$(mktemp)
        printf "%s" "InfraK3s-2026!" > "$TMPKEY"
        chmod 600 "$TMPKEY"

        clevis luks bind -y -k "$TMPKEY" -d /dev/sda3 tpm2 "{\"pcr_ids\":\"7\"}"

        rm -f "$TMPKEY"

        echo "[INFO] Regenerando initramfs..."
        update-initramfs -u -k all
      '
