apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infrawriter-git
  namespace: infrawriter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: infrawriter-git
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: GIT_REPO_URL
      remoteRef:
        key: app/infrawriter/git
        property: GIT_REPO_URL

    - secretKey: GIT_TOKEN
      remoteRef:
        key: app/infrawriter/git
        property: GIT_TOKEN

    - secretKey: GIT_BRANCH
      remoteRef:
        key: app/infrawriter/git
        property: GIT_BRANCH

    - secretKey: GIT_REPO_PATH
      remoteRef:
        key: app/infrawriter/git
        property: GIT_REPO_PATH

    - secretKey: GIT_USER_NAME
      remoteRef:
        key: app/infrawriter/git
        property: GIT_USER_NAME

    - secretKey: GIT_USER_EMAIL
      remoteRef:
        key: app/infrawriter/git
        property: GIT_USER_EMAIL