apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infrawriter-tls
  namespace: infrawriter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: infrawriter-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: certs/infrawriter-tls
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: certs/infrawriter-tls
        property: tls.key
