apiVersion: v1
kind: Secret
metadata:
  name: infrawriter-git
  namespace: infrawriter
type: Opaque
stringData:
  GIT_REPO_URL: "https://SirXavor:REMOVED@github.com/SirXavor/InfraServer.git"
  GIT_BRANCH: "main"
  GIT_REPO_PATH: "/data/repo"
  GIT_USER_NAME: "InfraWriter"
  GIT_USER_EMAIL: "infrawriter@manabo.org"
