apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-wildcard-tls
  namespace: wireguard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: wg-wildcard-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: certs/wg-wildcard-tls
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: certs/wg-wildcard-tls
        property: tls.key
