configMapGenerator:
  - name: provisioning-configs
    namespace: provisioning
    files:
      - 00-installer.yaml
      - 10-network.yaml
      - 20-profile-default-storage.yaml
      - 20-profile-noswap-storage.yaml
      - 90-host-aa-bb-cc-dd-ee-ff.yaml
      - provisioning/90-host-default.yaml