configMapGenerator:
  - name: provisioning-configs
    namespace: provisioning
    files:
      - base\00-installer.yaml
      - base\10-network.yaml
      - base\20-automation.yaml
      - profiles\20-profile-default-storage.yaml
      - profiles\20-profile-noswap-storage.yaml
      - hosts\90-host-aa-bb-cc-dd-ee-ff.yaml
      - hosts\90-host-default.yaml