apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: coredns-config
    namespace: dns
    behavior: replace
    literals: []
    files:
      - Corefile=Corefile
      - hosts=hosts

generatorOptions:
  disableNameSuffixHash: false
