apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrawriter
  namespace: infrawriter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: nginx
  rules:
    - host: infrawriter.tudominio.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: infrawriter-api
                port:
                  name: http

          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: infrawriter-frontend
          #       port:
          #         name: http
  tls:
    - hosts:
        - infrawriter.manabo.org
      secretName: infrawriter-tls