apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrawriter
  namespace: infrawriter
spec:
  ingressClassName: nginx
  rules:
    - host: infrawriter.manabo.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: infrawriter-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infrawriter-frontend
                port:
                  name: http
  tls:
    - hosts:
        - infrawriter.manabo.org
      secretName: infrawriter-tls
