kind: host
name: prueba_xavier
identity:
  mac:
  - 00-bb-dd-dd-ee-00
profile: noswap
hostname: prueba_xavier
provisioning:
  distro: ubuntu
  version: '24.04'
automation:
  repo:
    url: https://github.com/SirXavor/InfraServer.git
    local_path: /opt/InfraServer
    branch: main
  apply:
    playbook: playbooks/bootstrap.yaml
    interval: 1h
  roles:
  - automation
  - bootstrap-agent
  - k3s-edge
  - ccn-base
  vars: {}
apps:
  wg-home:
    kind: wireguard
    enabled: true
    values:
      url: wg.manabo.org
      port: 34534
      password: manabo
