kind: host
name: default

profile: default
hostname: default-node

automation:
  repo:
    url: "https://github.com/SirXavor/InfraServer.git"
    local_path: "/opt/InfraServer"
    branch: "main"
    sync_interval: "1h"    
  
  apply:
    playbook: playbooks/bootstrap.yaml
    interval: 1h

