kind: host
name: Espi-node
identity:
  mac:
  - aa-bb-cc-dd-00-00
profile: edge-node
hostname: Espi-node
provisioning:
  distro: rhel
  version: '9'
automation:
  repo:
    url: https://github.com/SirXavor/InfraServer.git
    local_path: /opt/InfraServer
    branch: main
  apply:
    playbook: playbooks/bootstrap.yaml
    interval: 1h
  roles:
  - bootstrap-agent
  - ccn-base
  - k3s-edge
  vars: {}
apps:
  instancia 1 wiregurd:
    kind: wireguard
    enabled: true
    values:
      url: wg.manabo.org
      port: 51280
      password: manbabo
