kind: host
name: aa-bb-cc-dd-ee-ff

profile: noswap
hostname: k3s-master

automation:
  repo:
    url: "https://github.com/SirXavor/InfraServer.git"
    local_path: "/opt/InfraServer"
    branch: "main"

  apply:
    playbook: "playbooks/bootstrap.yaml"
    interval: "1h"

  roles:
    - base-common

  vars:
    test_message: "Prueba de Ansible desde InfraServer"
    users:
      - name: xavor
        password: "$6$q7TEWg0Pi4Nayu3c$Ix0MYhRuNzksBAytU1C/cvB4ou5tLHbm5xHRzo9/zwcOKV25WC7UnCmznD9pYqOAh0nW68tB6RAgT5uXAJlHA."
        groups: ["sudo"]
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGjQLANlWCgoyQ5a2IO2TgcD5pIH5wPW55RXYlKlUAd Xavier@casa
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII1BmJqTSExkz9tUSdjAlfqMXyBzEzmgsy6RbQ6RCiK0 Xavor@Tader
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBglC0K5nuwx+DU8TcvEkrvQLRyY01hmTlZWTNka3qc Portatil Xavier

      - name: admin.c3s
        password: "$6$rPp1eCmX8PAkQz.9$BbbKexET59FkgsQDZMjUl46d4pu1mOp40fbpuiZETuRA.f6KVVYajxQCS6xPDRQAhJ7Bg/WXfihjmEyBOmRSw/"
        groups: ["sudo"]