apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftp-provisioning
  namespace: provisioning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tftp-provisioning
  template:
    metadata:
      labels:
        app: tftp-provisioning
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tftp-provisioning
        image: xavor/tftp-provisioning:2.0
        ports:
        - name: tftp
          containerPort: 69
          protocol: UDP
