apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tftp-provisioning
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SirXavor/InfraServer.git
    targetRevision: main
    path: tftp-provisioning
  destination:
    server: https://kubernetes.default.svc
    namespace: tftp-provisioning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
