apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioning-engine-settings
  namespace: provisioning
data:
  DS_URL: "https://boot.hermes.ranabo.com"
  TANG_URL: "https://tang.hermes.ranabo.com"
  REPO_URL: "https://github.com/SirXavor/InfraServer.git"
