apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provisioning-content
  namespace: provisioning
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi