configMapGenerator:
  - name: provisioning-configs
    namespace: provisioning
    files:
      - base/00-installer.yaml
      - base/10-network.yaml
      - base/30-automation.yaml
      - profiles/20-profile-default-storage.yaml
      - profiles/20-profile-noswap-storage.yaml
      - hosts/80-host-aa-bb-cc-dd-ee-ff.yaml
      - hosts/80-host-aa-bb-cc-dd-ee-00.yaml
      - hosts/80-host-default.yaml