resources:
  - namespace.yaml
  - deployment-kernel.yaml
  - service-kernel.yaml
  - ingress.yaml
  - pvc-iso.yaml
  - job-download.yaml

configMapGenerator:
  - name: provisioning-configs
    namespace: provisioning
    files:
      - configs/base/00-installer.yaml
      - configs/base/02-network.yaml

      - configs/profiles/default/01-storage.yaml
      - configs/profiles/noswap/01-storage.yaml

      - configs/hosts/default.yaml
      - configs/hosts/aa-bb-cc-dd-ee-ff.yaml

