resources:
  - namespace.yaml
  - deployment-kernel.yaml
  - service-kernel.yaml
  - ingress.yaml
  - pvc-iso.yaml
  - job-download.yaml

configMapGenerator:
  - name: provisioning-configs
    namespace: provisioning
    files:
      - configs/base/00-autoinstall.yaml
#      - configs/base/10-hardening-updates.yaml
#      - configs/base/20-hardening-antivirus.yaml
#      - configs/base/30-hardening-bloqueo-cuentas.yaml
#      - configs/base/40-hardening-bloqueo-dispositivos.yaml

#      - configs/hosts/default.yaml
#      - configs/hosts/aa-bb-cc-dd-ee-ff.yaml

#      - configs/profiles/k3s-single-node/00-k3s.yaml

generatorOptions:
  disableNameSuffixHash: true
