---
# ----------------------------
# PAM
# ----------------------------

pam_faillock_deny: 5
pam_faillock_fail_interval: 900
pam_faillock_unlock_time: 0
pam_faillock_admin_group: "sudo"

pam_pwquality_minlen: 10
pam_pwquality_dcredit: -1
pam_pwquality_ucredit: -1
pam_pwquality_lcredit: -1
pam_pwquality_ocredit: -1
pam_pwquality_difok: 4
pam_pwquality_maxrepeat: 3
pam_pwquality_gecoscheck: 1

pam_password_remember: 5

pam_pass_max_days: 60
pam_pass_min_days: 2
pam_pass_warn_age: 12
pam_pass_user_max_days: 730

pam_shell_timeout: 600

# ----------------------------
# SSH
# ----------------------------

ssh_port: 22
ssh_allow_groups:
  - sudo

# ----------------------------
# AUDITD
# ----------------------------

auditd_max_log_file: 50
auditd_num_logs: 10
auditd_space_left: 75